// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SKYHOOKV2CSV_TABLES_H_
#define FLATBUFFERS_GENERATED_SKYHOOKV2CSV_TABLES_H_

#include "flatbuffers/flatbuffers.h"

namespace Tables {

struct Table_FBX;

struct Record_FBX;

struct Table_FBX FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA_FORMAT_TYPE = 4,
    VT_SKYHOOK_VERSION = 6,
    VT_DATA_STRUCTURE_VERSION = 8,
    VT_DATA_SCHEMA_VERSION = 10,
    VT_DATA_SCHEMA = 12,
    VT_DB_SCHEMA_NAME = 14,
    VT_TABLE_NAME = 16,
    VT_DELETE_VECTOR = 18,
    VT_ROWS_VEC = 20,
    VT_NROWS = 22
  };
  int32_t data_format_type() const {
    return GetField<int32_t>(VT_DATA_FORMAT_TYPE, 0);
  }
  int32_t skyhook_version() const {
    return GetField<int32_t>(VT_SKYHOOK_VERSION, 0);
  }
  int32_t data_structure_version() const {
    return GetField<int32_t>(VT_DATA_STRUCTURE_VERSION, 0);
  }
  int32_t data_schema_version() const {
    return GetField<int32_t>(VT_DATA_SCHEMA_VERSION, 0);
  }
  const flatbuffers::String *data_schema() const {
    return GetPointer<const flatbuffers::String *>(VT_DATA_SCHEMA);
  }
  const flatbuffers::String *db_schema_name() const {
    return GetPointer<const flatbuffers::String *>(VT_DB_SCHEMA_NAME);
  }
  const flatbuffers::String *table_name() const {
    return GetPointer<const flatbuffers::String *>(VT_TABLE_NAME);
  }
  const flatbuffers::Vector<uint8_t> *delete_vector() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_DELETE_VECTOR);
  }
  const flatbuffers::Vector<flatbuffers::Offset<Record_FBX>> *rows_vec() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Record_FBX>> *>(VT_ROWS_VEC);
  }
  uint32_t nrows() const {
    return GetField<uint32_t>(VT_NROWS, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_DATA_FORMAT_TYPE) &&
           VerifyField<int32_t>(verifier, VT_SKYHOOK_VERSION) &&
           VerifyField<int32_t>(verifier, VT_DATA_STRUCTURE_VERSION) &&
           VerifyField<int32_t>(verifier, VT_DATA_SCHEMA_VERSION) &&
           VerifyOffset(verifier, VT_DATA_SCHEMA) &&
           verifier.VerifyString(data_schema()) &&
           VerifyOffset(verifier, VT_DB_SCHEMA_NAME) &&
           verifier.VerifyString(db_schema_name()) &&
           VerifyOffset(verifier, VT_TABLE_NAME) &&
           verifier.VerifyString(table_name()) &&
           VerifyOffset(verifier, VT_DELETE_VECTOR) &&
           verifier.VerifyVector(delete_vector()) &&
           VerifyOffset(verifier, VT_ROWS_VEC) &&
           verifier.VerifyVector(rows_vec()) &&
           verifier.VerifyVectorOfTables(rows_vec()) &&
           VerifyField<uint32_t>(verifier, VT_NROWS) &&
           verifier.EndTable();
  }
};

struct Table_FBXBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data_format_type(int32_t data_format_type) {
    fbb_.AddElement<int32_t>(Table_FBX::VT_DATA_FORMAT_TYPE, data_format_type, 0);
  }
  void add_skyhook_version(int32_t skyhook_version) {
    fbb_.AddElement<int32_t>(Table_FBX::VT_SKYHOOK_VERSION, skyhook_version, 0);
  }
  void add_data_structure_version(int32_t data_structure_version) {
    fbb_.AddElement<int32_t>(Table_FBX::VT_DATA_STRUCTURE_VERSION, data_structure_version, 0);
  }
  void add_data_schema_version(int32_t data_schema_version) {
    fbb_.AddElement<int32_t>(Table_FBX::VT_DATA_SCHEMA_VERSION, data_schema_version, 0);
  }
  void add_data_schema(flatbuffers::Offset<flatbuffers::String> data_schema) {
    fbb_.AddOffset(Table_FBX::VT_DATA_SCHEMA, data_schema);
  }
  void add_db_schema_name(flatbuffers::Offset<flatbuffers::String> db_schema_name) {
    fbb_.AddOffset(Table_FBX::VT_DB_SCHEMA_NAME, db_schema_name);
  }
  void add_table_name(flatbuffers::Offset<flatbuffers::String> table_name) {
    fbb_.AddOffset(Table_FBX::VT_TABLE_NAME, table_name);
  }
  void add_delete_vector(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> delete_vector) {
    fbb_.AddOffset(Table_FBX::VT_DELETE_VECTOR, delete_vector);
  }
  void add_rows_vec(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Record_FBX>>> rows_vec) {
    fbb_.AddOffset(Table_FBX::VT_ROWS_VEC, rows_vec);
  }
  void add_nrows(uint32_t nrows) {
    fbb_.AddElement<uint32_t>(Table_FBX::VT_NROWS, nrows, 0);
  }
  explicit Table_FBXBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  Table_FBXBuilder &operator=(const Table_FBXBuilder &);
  flatbuffers::Offset<Table_FBX> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Table_FBX>(end);
    return o;
  }
};

inline flatbuffers::Offset<Table_FBX> CreateTable_FBX(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t data_format_type = 0,
    int32_t skyhook_version = 0,
    int32_t data_structure_version = 0,
    int32_t data_schema_version = 0,
    flatbuffers::Offset<flatbuffers::String> data_schema = 0,
    flatbuffers::Offset<flatbuffers::String> db_schema_name = 0,
    flatbuffers::Offset<flatbuffers::String> table_name = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> delete_vector = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Record_FBX>>> rows_vec = 0,
    uint32_t nrows = 0) {
  Table_FBXBuilder builder_(_fbb);
  builder_.add_nrows(nrows);
  builder_.add_rows_vec(rows_vec);
  builder_.add_delete_vector(delete_vector);
  builder_.add_table_name(table_name);
  builder_.add_db_schema_name(db_schema_name);
  builder_.add_data_schema(data_schema);
  builder_.add_data_schema_version(data_schema_version);
  builder_.add_data_structure_version(data_structure_version);
  builder_.add_skyhook_version(skyhook_version);
  builder_.add_data_format_type(data_format_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<Table_FBX> CreateTable_FBXDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t data_format_type = 0,
    int32_t skyhook_version = 0,
    int32_t data_structure_version = 0,
    int32_t data_schema_version = 0,
    const char *data_schema = nullptr,
    const char *db_schema_name = nullptr,
    const char *table_name = nullptr,
    const std::vector<uint8_t> *delete_vector = nullptr,
    const std::vector<flatbuffers::Offset<Record_FBX>> *rows_vec = nullptr,
    uint32_t nrows = 0) {
  auto data_schema__ = data_schema ? _fbb.CreateString(data_schema) : 0;
  auto db_schema_name__ = db_schema_name ? _fbb.CreateString(db_schema_name) : 0;
  auto table_name__ = table_name ? _fbb.CreateString(table_name) : 0;
  auto delete_vector__ = delete_vector ? _fbb.CreateVector<uint8_t>(*delete_vector) : 0;
  auto rows_vec__ = rows_vec ? _fbb.CreateVector<flatbuffers::Offset<Record_FBX>>(*rows_vec) : 0;
  return Tables::CreateTable_FBX(
      _fbb,
      data_format_type,
      skyhook_version,
      data_structure_version,
      data_schema_version,
      data_schema__,
      db_schema_name__,
      table_name__,
      delete_vector__,
      rows_vec__,
      nrows);
}

struct Record_FBX FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RID = 4,
    VT_NULLBITS = 6,
    VT_DATA = 8
  };
  uint64_t RID() const {
    return GetField<uint64_t>(VT_RID, 0);
  }
  const flatbuffers::Vector<uint64_t> *nullbits() const {
    return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_NULLBITS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *data() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_RID) &&
           VerifyOffset(verifier, VT_NULLBITS) &&
           verifier.VerifyVector(nullbits()) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.VerifyVectorOfStrings(data()) &&
           verifier.EndTable();
  }
};

struct Record_FBXBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_RID(uint64_t RID) {
    fbb_.AddElement<uint64_t>(Record_FBX::VT_RID, RID, 0);
  }
  void add_nullbits(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> nullbits) {
    fbb_.AddOffset(Record_FBX::VT_NULLBITS, nullbits);
  }
  void add_data(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> data) {
    fbb_.AddOffset(Record_FBX::VT_DATA, data);
  }
  explicit Record_FBXBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  Record_FBXBuilder &operator=(const Record_FBXBuilder &);
  flatbuffers::Offset<Record_FBX> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Record_FBX>(end);
    return o;
  }
};

inline flatbuffers::Offset<Record_FBX> CreateRecord_FBX(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t RID = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> nullbits = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> data = 0) {
  Record_FBXBuilder builder_(_fbb);
  builder_.add_RID(RID);
  builder_.add_data(data);
  builder_.add_nullbits(nullbits);
  return builder_.Finish();
}

inline flatbuffers::Offset<Record_FBX> CreateRecord_FBXDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t RID = 0,
    const std::vector<uint64_t> *nullbits = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *data = nullptr) {
  auto nullbits__ = nullbits ? _fbb.CreateVector<uint64_t>(*nullbits) : 0;
  auto data__ = data ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*data) : 0;
  return Tables::CreateRecord_FBX(
      _fbb,
      RID,
      nullbits__,
      data__);
}

inline const Tables::Table_FBX *GetTable_FBX(const void *buf) {
  return flatbuffers::GetRoot<Tables::Table_FBX>(buf);
}

inline const Tables::Table_FBX *GetSizePrefixedTable_FBX(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Tables::Table_FBX>(buf);
}

inline bool VerifyTable_FBXBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Tables::Table_FBX>(nullptr);
}

inline bool VerifySizePrefixedTable_FBXBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Tables::Table_FBX>(nullptr);
}

inline void FinishTable_FBXBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Tables::Table_FBX> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTable_FBXBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Tables::Table_FBX> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Tables

#endif  // FLATBUFFERS_GENERATED_SKYHOOKV2CSV_TABLES_H_
